twig:
    default_path: '%kernel.project_dir%/templates'
    cache: '%kernel.cache_dir%/twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

when@test:
    twig:
        strict_variables: true
